"""qPCR plotting logic for reviewed extracted summary tables."""

from __future__ import annotations

import argparse
import math
from numbers import Real
from pathlib import Path
import re
import sys

import pandas as pd

from tools_for_pharma.qpcr.common import (
    INDIVIDUAL_RQ_COLUMN,
    MEAN_RQ_COLUMN,
    PLOTDATA_SHEET_PREFIX,
    REFERENCE_SOURCE_COLUMN,
    SEM_COLUMN,
    clean_text,
    is_plotdata_sheet_name,
)
from tools_for_pharma.shared.excel_utils import list_excel_sheets


INPUT_FILE = Path("qpcr_summary.xlsx")
PLOT_MODE_SPLIT = "split"
PLOT_MODE_COMBINED = "combined"
PLOT_MODE_BOTH = "both"
PLOT_MODE_CHOICES = [PLOT_MODE_SPLIT, PLOT_MODE_COMBINED, PLOT_MODE_BOTH]

REQUIRED_COLUMNS = [
    "Group",
    "Compound ID",
    REFERENCE_SOURCE_COLUMN,
    MEAN_RQ_COLUMN,
    SEM_COLUMN,
]

FONT_FAMILY = "Arial"
FONT_SIZE = 15
TITLE_FONT_SIZE = 22
AXIS_LABEL_FONT_SIZE = 20
TICK_LABEL_FONT_SIZE = 16
LEGEND_FONT_SIZE = 16
SPLIT_FIGURE_HEIGHT = 9.0
COMBINED_FIGURE_HEIGHT = 9.5
COMBINED_LAYOUT_TOP = 0.80
COMBINED_LEGEND_TOP = 0.91
MAX_LEGEND_COLUMNS = 4
TEXT_COLOR = "#222222"
AXIS_COLOR = "#444444"
GRID_COLOR = "#E4E4E4"
BASELINE_COLOR = "#7A7A7A"
REFERENCE_PALETTE = [
    "#4E79A7",
    "#59A14F",
    "#F28E2B",
    "#B07AA1",
    "#E15759",
    "#76B7B2",
]
SCATTER_EDGE_COLOR = "#FFFFFF"
SCATTER_SIZE = 30
BAR_OUTLINE_WIDTH = 1.45
ERROR_LINE_WIDTH = 1.05
AXIS_SPINE_OFFSET_POINTS = 7

BAR_KEY_COLUMNS = ["Group", "Compound ID", REFERENCE_SOURCE_COLUMN]


def identifier_label(value: object) -> str:
    """Format numeric identifiers without changing genuine text identifiers."""
    if isinstance(value, Real) and not isinstance(value, bool):
        number = float(value)
        if math.isfinite(number):
            if number.is_integer():
                return str(int(number))
            return f"{number:g}"
    return clean_text(value)


def group_label(row: pd.Series) -> str:
    return f"{identifier_label(row['Group'])} | {identifier_label(row['Compound ID'])}"


def sanitize_filename(value: object) -> str:
    name = re.sub(r"[^A-Za-z0-9._-]+", "_", clean_text(value)).strip("_")
    return name or "plot"


def reference_color(reference_source: object, reference_sources: list[object]) -> str:
    try:
        index = reference_sources.index(reference_source)
    except ValueError:
        index = 0
    return REFERENCE_PALETTE[index % len(REFERENCE_PALETTE)]


def bar_summary(summary: pd.DataFrame) -> pd.DataFrame:
    """Return one mean/SEM row per plotted bar while preserving input order."""
    return summary.drop_duplicates(subset=BAR_KEY_COLUMNS, keep="first").copy()


def jitter_positions(center: float, count: int, half_width: float) -> list[float]:
    if count <= 0:
        return []
    if count == 1:
        return [center]
    return [
        center - half_width + (2 * half_width * index / (count - 1))
        for index in range(count)
    ]


def add_individual_points(
    axis,
    center: float,
    values: list[float],
    half_width: float,
    color: str,
) -> None:
    if not values:
        return
    axis.scatter(
        jitter_positions(center, len(values), half_width),
        values,
        s=SCATTER_SIZE,
        color=color,
        edgecolors=SCATTER_EDGE_COLOR,
        linewidths=0.65,
        alpha=0.94,
        zorder=4,
    )


def default_plot_dir(input_file: Path) -> Path:
    return input_file.with_name(input_file.stem)


def plotdata_sheets(input_file: Path) -> list[str]:
    return [
        sheet
        for sheet in list_excel_sheets(input_file)
        if is_plotdata_sheet_name(sheet)
    ]


def resolve_summary_sheet(input_file: Path, sheet_name: str | None) -> str:
    if sheet_name is not None:
        if not is_plotdata_sheet_name(sheet_name):
            raise ValueError(
                f"Sheet '{sheet_name}' is not a qPCR plot-data sheet. "
                f"Choose a sheet whose name starts with '{PLOTDATA_SHEET_PREFIX}'."
            )
        return sheet_name

    candidates = plotdata_sheets(input_file)
    if not candidates:
        raise ValueError(
            f"No qPCR plot-data sheet found in {input_file}. "
            f"Run extraction first, then choose a sheet whose name starts with "
            f"'{PLOTDATA_SHEET_PREFIX}'."
        )
    return candidates[-1]


def validate_summary_columns(summary: pd.DataFrame, sheet_name: str | int | None = None) -> None:
    missing_columns = [
        column for column in REQUIRED_COLUMNS
        if column not in summary.columns
    ]
    if missing_columns:
        missing = ", ".join(missing_columns)
        location = f" in sheet '{sheet_name}'" if sheet_name is not None else ""
        raise ValueError(
            f"Input summary{location} is missing required columns: {missing}. "
            "Choose a sheet generated by qPCR_extract_excel_table.py."
        )


def get_pyplot():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": [FONT_FAMILY, "DejaVu Sans", "Calibri", "Arial"],
            "font.size": FONT_SIZE,
            "axes.titlesize": TITLE_FONT_SIZE,
            "axes.labelsize": AXIS_LABEL_FONT_SIZE,
            "axes.titleweight": "bold",
            "axes.edgecolor": AXIS_COLOR,
            "axes.labelcolor": TEXT_COLOR,
            "xtick.color": TEXT_COLOR,
            "ytick.color": TEXT_COLOR,
            "legend.fontsize": LEGEND_FONT_SIZE,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
        }
    )
    return plt


def read_summary(input_file: Path, sheet_name: str | None = None) -> pd.DataFrame:
    sheet = resolve_summary_sheet(input_file, sheet_name)
    summary = pd.read_excel(input_file, sheet_name=sheet)
    validate_summary_columns(summary, sheet)

    summary[MEAN_RQ_COLUMN] = pd.to_numeric(summary[MEAN_RQ_COLUMN], errors="coerce")
    summary[SEM_COLUMN] = pd.to_numeric(summary[SEM_COLUMN], errors="coerce")
    if INDIVIDUAL_RQ_COLUMN in summary.columns:
        summary[INDIVIDUAL_RQ_COLUMN] = pd.to_numeric(
            summary[INDIVIDUAL_RQ_COLUMN],
            errors="coerce",
        )
    else:
        summary[INDIVIDUAL_RQ_COLUMN] = pd.NA
    summary = summary.dropna(subset=[MEAN_RQ_COLUMN, SEM_COLUMN])
    if summary.empty:
        raise ValueError("The selected summary sheet has no plottable MEAN RQ/SEM rows.")
    summary["Plot label"] = summary.apply(group_label, axis=1)
    return summary


def finish_plot(axis, title: str, labels: list[str], output_path: Path) -> list[Path]:
    plt = get_pyplot()
    png_path = output_path.with_suffix(".png")
    svg_path = output_path.with_suffix(".svg")
    if axis.figure.legends:
        axis.figure.suptitle(
            title,
            y=0.99,
            color=TEXT_COLOR,
            fontsize=TITLE_FONT_SIZE,
            fontweight="bold",
        )
    else:
        axis.set_title(title, pad=12, color=TEXT_COLOR)
    axis.set_ylabel(MEAN_RQ_COLUMN)
    axis.axhline(
        1,
        color=BASELINE_COLOR,
        linewidth=0.85,
        linestyle=(0, (4, 3)),
        alpha=0.75,
        zorder=0,
    )
    axis.yaxis.grid(True, color=GRID_COLOR, linewidth=0.55)
    axis.set_axisbelow(True)
    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)
    axis.spines["left"].set_linewidth(0.8)
    axis.spines["bottom"].set_linewidth(0.8)
    axis.spines["left"].set_position(("outward", AXIS_SPINE_OFFSET_POINTS))
    axis.spines["bottom"].set_position(("outward", AXIS_SPINE_OFFSET_POINTS))
    axis.set_xticks(range(len(labels)))
    axis.set_xticklabels(
        labels,
        rotation=90,
        ha="center",
        fontsize=TICK_LABEL_FONT_SIZE,
    )
    axis.tick_params(axis="both", length=3, width=0.8)
    axis.margins(x=0.01)
    axis.set_ylim(bottom=0)
    if axis.figure.legends:
        axis.figure.tight_layout(rect=(0, 0, 1, COMBINED_LAYOUT_TOP))
    else:
        axis.figure.tight_layout()
    png_path.parent.mkdir(parents=True, exist_ok=True)
    axis.figure.savefig(png_path, dpi=300, bbox_inches="tight")
    axis.figure.savefig(svg_path, bbox_inches="tight")
    plt.close(axis.figure)
    return [png_path, svg_path]


def plot_split_by_reference(summary: pd.DataFrame, plot_dir: Path) -> list[Path]:
    plt = get_pyplot()
    output_paths = []
    bars = bar_summary(summary)
    reference_sources = list(dict.fromkeys(bars[REFERENCE_SOURCE_COLUMN].tolist()))

    for reference_source, subset in bars.groupby(REFERENCE_SOURCE_COLUMN, sort=False):
        series_color = reference_color(reference_source, reference_sources)
        labels = subset["Plot label"].tolist()
        y_values = subset[MEAN_RQ_COLUMN].tolist()
        y_errors = subset[SEM_COLUMN].tolist()
        figure_width = max(13, len(labels) * 0.60)
        _figure, axis = plt.subplots(figsize=(figure_width, SPLIT_FIGURE_HEIGHT))
        axis.bar(
            range(len(labels)),
            y_values,
            yerr=y_errors,
            capsize=3.2,
            color="none",
            edgecolor=series_color,
            error_kw={
                "elinewidth": ERROR_LINE_WIDTH,
                "ecolor": series_color,
                "capthick": ERROR_LINE_WIDTH,
            },
            linewidth=BAR_OUTLINE_WIDTH,
            zorder=2,
        )
        source_points = summary[summary[REFERENCE_SOURCE_COLUMN] == reference_source]
        for x_position, plot_label in enumerate(labels):
            values = (
                source_points.loc[
                    source_points["Plot label"] == plot_label,
                    INDIVIDUAL_RQ_COLUMN,
                ]
                .dropna()
                .astype(float)
                .tolist()
            )
            add_individual_points(
                axis,
                x_position,
                values,
                half_width=0.16,
                color=series_color,
            )
        output_path = plot_dir / f"{sanitize_filename(reference_source)}.png"
        output_paths.extend(
            finish_plot(
                axis,
                f"qPCR MEAN RQ by group - {reference_source}",
                labels,
                output_path,
            )
        )
    return output_paths


def plot_combined_references(summary: pd.DataFrame, plot_dir: Path) -> list[Path]:
    plt = get_pyplot()
    bars = bar_summary(summary)
    labels = list(dict.fromkeys(bars["Plot label"].tolist()))
    reference_sources = list(dict.fromkeys(bars[REFERENCE_SOURCE_COLUMN].tolist()))
    if not labels or not reference_sources:
        return []

    figure_width = max(15, len(labels) * 0.82)
    figure, axis = plt.subplots(figsize=(figure_width, COMBINED_FIGURE_HEIGHT))
    bar_width = min(0.26, 0.82 / max(len(reference_sources), 1))
    first_offset = -bar_width * (len(reference_sources) - 1) / 2

    for source_index, reference_source in enumerate(reference_sources):
        series_color = REFERENCE_PALETTE[source_index % len(REFERENCE_PALETTE)]
        subset = bars[bars[REFERENCE_SOURCE_COLUMN] == reference_source]
        by_label = {
            label: row
            for label, row in subset.set_index("Plot label").iterrows()
        }
        x_values = [
            index + first_offset + source_index * bar_width
            for index in range(len(labels))
        ]
        y_values = [
            by_label[label][MEAN_RQ_COLUMN] if label in by_label else 0
            for label in labels
        ]
        y_errors = [
            by_label[label][SEM_COLUMN] if label in by_label else 0
            for label in labels
        ]
        axis.bar(
            x_values,
            y_values,
            width=bar_width,
            yerr=y_errors,
            capsize=2.6,
            label=reference_source,
            color="none",
            edgecolor=series_color,
            error_kw={
                "elinewidth": ERROR_LINE_WIDTH,
                "ecolor": series_color,
                "capthick": ERROR_LINE_WIDTH,
            },
            linewidth=BAR_OUTLINE_WIDTH,
            zorder=2,
        )
        source_points = summary[summary[REFERENCE_SOURCE_COLUMN] == reference_source]
        for x_position, label in zip(x_values, labels):
            values = (
                source_points.loc[
                    source_points["Plot label"] == label,
                    INDIVIDUAL_RQ_COLUMN,
                ]
                .dropna()
                .astype(float)
                .tolist()
            )
            add_individual_points(
                axis,
                x_position,
                values,
                half_width=bar_width * 0.34,
                color=series_color,
            )

    handles, legend_labels = axis.get_legend_handles_labels()
    figure.legend(
        handles,
        legend_labels,
        frameon=False,
        ncols=min(len(reference_sources), MAX_LEGEND_COLUMNS),
        loc="upper center",
        bbox_to_anchor=(0.5, COMBINED_LEGEND_TOP),
        handlelength=1.8,
        columnspacing=1.2,
    )
    output_path = plot_dir / "combined_reference_sources.png"
    return finish_plot(
        axis,
        "qPCR MEAN RQ by group and reference source",
        labels,
        output_path,
    )


def create_plots(
    input_file: Path,
    output_dir: Path | None = None,
    plot_mode: str = PLOT_MODE_BOTH,
    sheet_name: str | None = None,
) -> list[Path]:
    summary = read_summary(input_file, sheet_name)
    if summary.empty:
        return []

    plot_dir = output_dir if output_dir else default_plot_dir(input_file)
    output_paths = []
    if plot_mode in {PLOT_MODE_SPLIT, PLOT_MODE_BOTH}:
        output_paths.extend(plot_split_by_reference(summary, plot_dir))
    if plot_mode in {PLOT_MODE_COMBINED, PLOT_MODE_BOTH}:
        output_paths.extend(plot_combined_references(summary, plot_dir))
    return output_paths


def choose_sheet_gui(root, input_file: Path) -> str | None:
    import tkinter as tk
    from tkinter import ttk

    sheets = list_excel_sheets(input_file)
    if len(sheets) <= 1:
        return None

    plotdata = [sheet for sheet in sheets if is_plotdata_sheet_name(sheet)]
    default_sheet = plotdata[-1] if plotdata else sheets[-1]
    selected = {"value": default_sheet}
    window = tk.Toplevel(root)
    window.title("Select plot data sheet")
    window.resizable(False, False)
    window.columnconfigure(1, weight=1)

    ttk.Label(window, text="Worksheet").grid(
        row=0, column=0, padx=16, pady=(16, 8), sticky="w"
    )
    sheet_var = tk.StringVar(value=default_sheet)
    sheet_box = ttk.Combobox(
        window,
        textvariable=sheet_var,
        values=sheets,
        state="readonly",
        width=max(30, min(60, max(len(sheet) for sheet in sheets) + 2)),
    )
    sheet_box.grid(row=0, column=1, padx=16, pady=(16, 8), sticky="ew")

    buttons = ttk.Frame(window)
    buttons.grid(row=1, column=0, columnspan=2, padx=16, pady=(8, 16), sticky="e")

    def use_sheet() -> None:
        selected["value"] = sheet_var.get()
        window.destroy()

    def cancel() -> None:
        selected["value"] = None
        window.destroy()

    ttk.Button(buttons, text="Cancel", command=cancel).grid(row=0, column=0, padx=(0, 8))
    ttk.Button(buttons, text="Continue", command=use_sheet).grid(row=0, column=1)
    window.protocol("WM_DELETE_WINDOW", cancel)
    window.bind("<Return>", lambda _event: use_sheet())
    window.bind("<Escape>", lambda _event: cancel())
    window.grab_set()
    sheet_box.focus_set()
    window.wait_window()
    return selected["value"]


def run_gui() -> int:
    import tkinter as tk
    from tkinter import filedialog, messagebox, ttk

    root = tk.Tk()
    root.withdraw()

    try:
        input_path = filedialog.askopenfilename(
            title="Select reviewed qPCR plot-data Excel file",
            filetypes=[
                ("Excel files", "*.xlsx *.xlsm"),
                ("All files", "*.*"),
            ],
        )
        if not input_path:
            return 0

        input_file = Path(input_path)
        sheet_name = choose_sheet_gui(root, input_file)
        if sheet_name is None and len(list_excel_sheets(input_file)) > 1:
            return 0

        mode_window = tk.Toplevel(root)
        mode_window.title("Plot options")
        mode_window.resizable(False, False)
        ttk.Label(mode_window, text="Plot style").grid(
            row=0, column=0, padx=16, pady=(16, 8), sticky="w"
        )
        mode_var = tk.StringVar(value=PLOT_MODE_BOTH)
        mode_box = ttk.Combobox(
            mode_window,
            textvariable=mode_var,
            values=PLOT_MODE_CHOICES,
            state="readonly",
            width=20,
        )
        mode_box.grid(row=0, column=1, padx=16, pady=(16, 8), sticky="ew")
        selected = {"continue": False}

        def continue_with_mode() -> None:
            selected["continue"] = True
            mode_window.destroy()

        ttk.Button(
            mode_window,
            text="Continue",
            command=continue_with_mode,
        ).grid(row=1, column=0, columnspan=2, padx=16, pady=(8, 16), sticky="e")
        mode_window.protocol("WM_DELETE_WINDOW", mode_window.destroy)
        mode_window.grab_set()
        mode_box.focus_set()
        mode_window.wait_window()
        if not selected["continue"]:
            return 0

        output_dir = default_plot_dir(input_file)
        plot_paths = create_plots(input_file, output_dir, mode_var.get(), sheet_name)
        message = f"Created {len(plot_paths)} plot files."
        if plot_paths:
            message += f"\n\nSaved to:\n{output_dir}"
        messagebox.showinfo("Done", message)
        return 0
    except Exception as error:
        messagebox.showerror("qPCR plotting failed", str(error))
        return 1
    finally:
        root.destroy()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create qPCR plots from a reviewed extracted plot-data table."
    )
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=INPUT_FILE,
        help=f"Extracted qPCR plot-data .xlsx file. Defaults to {INPUT_FILE}.",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        type=Path,
        help=(
            "Folder for plot PNG and SVG files. Defaults to a subfolder beside the input "
            "workbook with the same name as the workbook stem."
        ),
    )
    parser.add_argument(
        "--sheet",
        help=(
            "Worksheet containing extracted qPCR plot data. Defaults to the last "
            f"sheet whose name starts with '{PLOTDATA_SHEET_PREFIX}'."
        ),
    )
    parser.add_argument(
        "--plot",
        choices=PLOT_MODE_CHOICES,
        default=PLOT_MODE_BOTH,
        help="split = one plot per reference source; combined = one grouped plot.",
    )
    parser.add_argument(
        "--gui",
        action="store_true",
        help="Choose the reviewed plot-data file, sheet, and plot mode with dialogs.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.gui:
        return run_gui()

    try:
        plot_paths = create_plots(args.input, args.output_dir, args.plot, args.sheet)
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    if not plot_paths:
        print("No plots were created.")
        return 0

    print("Plots:")
    for plot_path in plot_paths:
        print(f"  {plot_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
